// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgSq2SXS4CLq7KkQ4xRX5E0rKsU3o_e-c',
    appId: '1:493303713712:web:d3c870309c8e2eb7129075',
    messagingSenderId: '493303713712',
    projectId: 'map-app-12ff9',
    authDomain: 'map-app-12ff9.firebaseapp.com',
    storageBucket: 'map-app-12ff9.firebasestorage.app',
    measurementId: 'G-XSB5C2S4DJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7IZNt46xIDDlK2_CaXQ3Oe_MrcIxOpQs',
    appId: '1:493303713712:android:25b6eee3e6aa854e129075',
    messagingSenderId: '493303713712',
    projectId: 'map-app-12ff9',
    storageBucket: 'map-app-12ff9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApf0fZfccbqxkOja5dzNDGjHlRV5BjxDk',
    appId: '1:493303713712:ios:4fced7de1c9e05a8129075',
    messagingSenderId: '493303713712',
    projectId: 'map-app-12ff9',
    storageBucket: 'map-app-12ff9.firebasestorage.app',
    iosBundleId: 'com.example.mapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApf0fZfccbqxkOja5dzNDGjHlRV5BjxDk',
    appId: '1:493303713712:ios:4fced7de1c9e05a8129075',
    messagingSenderId: '493303713712',
    projectId: 'map-app-12ff9',
    storageBucket: 'map-app-12ff9.firebasestorage.app',
    iosBundleId: 'com.example.mapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgSq2SXS4CLq7KkQ4xRX5E0rKsU3o_e-c',
    appId: '1:493303713712:web:bd3f5e1099c01d3e129075',
    messagingSenderId: '493303713712',
    projectId: 'map-app-12ff9',
    authDomain: 'map-app-12ff9.firebaseapp.com',
    storageBucket: 'map-app-12ff9.firebasestorage.app',
    measurementId: 'G-637MXR21R4',
  );
}
